name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: iterative/setup-cml@v2
      - name: install packages
        run: make install
      - name: Format
        run: make format
      - name: Train
        run: make train
      - name: Evaluation
        env: 
          REPO_TOKEN: ${{  secrets.GITHUB_TOKEN  }}   # GITHUB TOKEN BUILT IN ON GITHUB REPO
        run: make eval
      - name: Update branch
        env:
          NAME: ${{  secrets.USER_NAME  }}
          EMAIL: ${{  secrets.USER_EMAIL  }}
        # run: make update-branch USER_NAME=$NAME USER_EMAIL=$EMAIL BRANCH=${{ github.head_ref  }}
        run: |
          git config --local user.email $EMAIL
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add Changes"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{  secrets.GITHUB_TOKEN  }}
          branch: ${{  github.head_ref  }}
          repository: "AvivTahar/drug_classification"